# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/dumb_inputs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63lient/dumb_inputs.proto\"R\n\x0bInputAction\x12!\n\tkeyEvents\x18\x01 \x03(\x0b\x32\x0e.KeyboardEvent\x12\x0f\n\x07mouseDx\x18\x02 \x01(\x11\x12\x0f\n\x07mouseDy\x18\x03 \x01(\x11\";\n\rKeyboardEvent\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\teventType\x18\x02 \x01(\x0e\x32\n.EventType*#\n\tEventType\x12\t\n\x05PRESS\x10\x00\x12\x0b\n\x07RELEASE\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client.dumb_inputs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVENTTYPE._serialized_start=173
  _EVENTTYPE._serialized_end=208
  _INPUTACTION._serialized_start=28
  _INPUTACTION._serialized_end=110
  _KEYBOARDEVENT._serialized_start=112
  _KEYBOARDEVENT._serialized_end=171
# @@protoc_insertion_point(module_scope)
